### ISSUE TITLE
Junction has no definition

### ISSUE THREAD

**Issue by gdschut** [Interoperable-data/ERA-Ontology-3.1.0#24]
What is meant with Junction? https://era-web.linkeddata.es/doc/index-en.html#Junction
It has no definition.
Is it a switch? Or the Junction on Macro level? 
Or anything else?

**Comment by gatemezing** [comment]
Dear @gdschut , I think you are using a very old link. You can find the latest definition here https://linkedvocabs.org/data/era-ontology/3.1.0/doc/index-en.html#Junction, instead of the era-web domain.
It is declared to be disjoint with a Switch that need to be defined. Please, don't hesitate to send us any good definition as an expert of infrastructure. Thank you!

**Comment by gdschut** [comment]
Sorry for using an old version. 
Perhaps it would be helpfull if the published and development version would be on the same envirionment, and if they linked to each other?
Issue can be closed.

**Comment by gatemezing** [comment]
Yes, we will find a way to clarify the environment when we port the current documentation in ERA namespace. Thank you @gdschut !!

**Comment by gatemezing** [comment]
This issue can be closed according to the latest update of the ontology
